spring:
  redis:
    database: 1
    host: 127.0.0.1
    password: 123456
  application:
    name: dataStoragePlatform-server
  output:
    ansi:
      enabled: always
  mvc:
    servlet:
      load-on-startup: 1
  servlet:
    multipart:
      max-file-size: 3072MB
      max-request-size: 3072MB

  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/dataStoragePlatform?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useSSl=true&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:mappers/**/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: env,beans

swagger2:
  show: true
  group-name: ${spring.application.name}
  base-package: com.zyh432
  title: dataStoragePlatform-server docs
  description: dataStoragePlatform-server docs
  terms-of-service-url: http://127.0.0.1:${server.port}
  contact-name: panghu
  contact-url: https://blog.panghu.com
  contact-email: 790585941@qq.com
  version: 1.0



com:
  zyh432:
    server:
      share-prefix: http://127.0.0.1:5173/
    bloom:
      filter:
        local:
          items:
            - name: SHARE_SIMPLE_DETAIL
              funnel-type-name: LONG
              expected-insertions: 100000
              fpp: 0.01


#com:
#  zyh432:
#      storage:
#        engine:
#          oss:
#            bucket-name: datastorageplatform-zyh432-test-1
#            endpoint: oss-cn-beijing.aliyuncs.com
#            access-key-id: LTAI5tALf8iTdNpcvh3goJQb
#            access-key-secret: fiIiMah0E0UTY7KgGVGcwZ7AE6w8Xr
#            auto-create-bucket: true
#          fdfs:
#            connect-timeout: 600
#            tracker-list:
#              - 39.98.37.93:22122
#            group: group1