spring:
  redis:
    database=1
    host=127.0.0.1
    password=123456
  application:
    name: dataStoragePlatform-server
  output:
    ansi:
      enabled: always
  mvc:
    servlet:
      load-on-startup: 1
  servlet:
    multipart:
      max-file-size: 3072MB
      max-request-size: 3072MB

  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/dataStoragePlatform?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useSSl=true&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:mappers/**/*.xml

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: env,beans

swagger2:
  show: true
  group-name: ${spring.application.name}
  base-package: com.zyh432
  title: dataStoragePlatform-server docs
  description: dataStoragePlatform-server docs
  terms-of-service-url: http://127.0.0.1:${server.port}
  contact-name: panghu
  contact-url: https://blog.panghu.com
  contact-email: 790585941@qq.com
  version: 1.0